### ISSUE TITLE
qmk header files

### ISSUE THREAD

**Issue by caga** [binarybottle/engram#13]
Dear @binarybottle 

i send you two standard header files (should go under: qmk_firmware/quantum/keymap_extras) that i told you i would do. i have not made a pull request from qmk directly (i feel my repo is in total mass) maybe you would. These are just for aliasing and shifted chars lookup table while using sendstring in your qmk macros. 

[keymap_engram.h](https://github.com/caga/qmk_firmware/blob/master/quantum/keymap_extras/keymap_engram.h)
[sendstring_engram.h](https://github.com/caga/qmk_firmware/blob/master/quantum/keymap_extras/sendstring_engram.h)

i admit that i understand the function of these header files wrong at first as i am very new to programming keyboards and qmk. These above are infact standart aliasing headers. colemak, workman, dvorak have them and now engram. 

Though you or @sunaku  may want to review and edit before a pull request.

i have also completed two other header for universal engram unicode layout, they partially work, though i have some issues to solve. i may need help soon for review. but as unicodes are too big and take up great portion of the memory of my keyboard, i have second thoughts about them. Here they are: 
[unicodes header](https://github.com/caga/qmk_firmware/blob/master/quantum/unicodes.h)
[universal engram header](https://github.com/caga/qmk_firmware/blob/master/quantum/keymap_extras/keymap_universal_engram.h)
[prototype plank keymap.c using universal engram header](https://github.com/caga/qmk_firmware/blob/master/keyboards/bm40hsrgb/keymaps/caga/keymap.c) (comments are not modified in this file, sorry)

please take care.
caga

**Comment by binarybottle** [comment]
@caga -- Thank you!

@sunaku -- Would you be able to help review this?

**Comment by sunaku** [comment]
I'm not familiar enough with QMK to review the PR. :sweat_smile:  However, the top level `keymap_engram.h` file looks good to me:
* I would suggest changing the `EN_` prefix to `ENGRAM_` for clarity.  If 2-letter abbreviation is strictly necessary, perhaps `NG_` would better phonetically represent the word "Engram" (because `EN_` reads as "English" to me).

**Comment by binarybottle** [comment]
@caga -- I agree with @sunaku's suggestion regarding pre-pending with ENGRAM_ or something equally identifiable.  I also don't have experience with qmk, so how about you do a pull request and if it works for you, great! If it doesn't work for others, then perhaps we will get further suggestions or contributions...

**Comment by caga** [comment]
Dear @binarybottle  , @sunaku 
Defacto standart is to use 2-letter abbreviation, though it is not strict. But the more longer the more harder for people to use keycodes. i have made and will make also some other minor changes, and after testing i make pull request from qmk.

i am also about to finish preparing a 6 level engram layout (desingned in mind for a 47 keys planck build but infact it is general) on @sunaku 's code. :smile:  i may want a pull request after it finished soon too @binarybottle .

Thank you guys. See you. :v:

**Comment by caga** [comment]
Linux 6 layer layout:
issue https://github.com/binarybottle/engram/issues/16
