### ISSUE TITLE
linux 6 layer layout

### ISSUE THREAD

**Issue by caga** [binarybottle/engram#16]
Dear @binarybottle and @sunaku 

i finished working prototype but could not prepare a proper documentation and could not integrate it on @sunaku 's installer. As something has came up and i will not be able to work on it for a while, So i just want to copy paste here the layout. 

it has 4 additional layers other than the base and shift layer of the original layout. These are lalt, lalt+shift, ralt, ralt+shift.
Alt layers basically lowers half of the number row  and half of the Function row to first alphabet layer (byo...) . 

lalt lowers the left half of the Function row and right half of the number row:
f1 f2 f3 f4 f5 6 7 8 9 0 ] /
ralt lowers the left half. 
1 2 3 4 5 f6 f7 f8 f9 f10...
so if you want to type 1 it is ralt+b if you want to type 8 it is lalt+d. if you want to press f1 it is lalt+b etc...

Shift+Alt layers are for corresponding symbols under the numbers.

Also lalt layer adds arrow keys under htsn letters. also add a delete key to "."
Additionally lalt+shift adds Backspace, Tab, Return under hts.

There are also some turkish letters on ralt level just for myself.

This can be improved more , can be added lots of things to layers like multimedia keys and even unicode emojis etc.
it is working on my system as it is now. 

Sorry for not submitting a well documented and finished code.  But i believe @sunaku can make it work and try as he uses linux and know about configuring xkb. 
By the way, which OS do you use @binarybottle ?

Anyways, sorry again for a post like that. Here is the partial layout xkb config:

//ENGRAM//BEGIN
// Arno's Engram keyboard layout v2.0 Six Level Layout - https://engram.dev
// This layout is designed for a modified 47 key planck clone. Though it can be used for others standard keyboards if one */
// may want to move fingers less while typing. Some keysyms are repeated to support different keyboard shape factors. You */
// may change the defaults to your convenience and liking. 
partial alphanumeric_keys

xkb_symbols "engram47"
{
	include "us(basic)"
  include "level3(lalt_switch)"
  include "level5(ralt_switch)"
  key.type[Group1] = "EIGHT_LEVEL";

//                BASE,         SHIFT,        LALT,      LALT+SHIFT,  RALT,      RALT+SHIFT
	key <TLDE> { [  bracketleft,  braceleft,    F12,       NoSymbol,    NoSymbol,  NoSymbol ] }; // [{
	key <AE01> { [            1,  bar,          NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol ] }; // 1|
	key <AE02> { [            2,  equal,        NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol ] }; // 2=
	key <AE03> { [            3,  asciitilde,   NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol ] }; // 3~
	key <AE04> { [            4,  plus,         NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol ] }; // 4+
	key <AE05> { [            5,  less,         NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol ] }; // 5<
	key <AE06> { [            6,  greater,      NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol ] }; // 6>
	key <AE07> { [            7,  asciicircum,  NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol ] }; // 7^
	key <AE08> { [            8,  ampersand,    NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol ] }; // 8&
	key <AE09> { [            9,  percent,      NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol ] }; // 9%
	key <AE10> { [            0,  asterisk,     NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol ] }; // 0*
	key <AE11> { [ bracketright,  braceright,   NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol ] }; // ]}
	key <AE12> { [        slash,  backslash,    NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol ] }; // /\

//                BASE,         SHIFT,             LALT,      LALT+SHIFT,   RALT,         RALT+SHIFT
	key <AD01> { [            b,  B,                 F1,        NoSymbol,     1,            bar                 ] }; // bB
	key <AD02> { [            y,  Y,                 F2,        NoSymbol,     2,            equal               ] }; // yY
	key <AD03> { [            o,  O,                 F3,        NoSymbol,     3,            asciitilde          ] }; // oO
	key <AD04> { [            u,  U,                 F4,        NoSymbol,     4,            plus                ] }; // uU
	key <AD05> { [   apostrophe,  parenright,        F5,        NoSymbol,     5,            less                ] }; // '(
	key <AD06> { [     quotedbl,  parenright,        6,         greater,      F6,           NoSymbol ] }; // ")
	key <AD07> { [            l,  L,                 7,         asciicircum,  F7,           NoSymbol ] }; // lL
	key <AD08> { [            d,  D,                 8,         ampersand,    F8,           NoSymbol ] }; // dD
	key <AD09> { [            w,  W,                 9,         percent,      F9,           NoSymbol ] }; // wW
	key <AD10> { [            v,  V,                 0,         asterisk,     F10,          NoSymbol ] }; // vV
	key <AD11> { [            z,  Z,                 gbreve,Gbreve,     bracketleft,  braceleft ] }; // zZ
	key <AD12> { [   numbersign,  dollar ] }; // #$
	key <BKSL> { [           at,  grave ] }; // @`

//                BASE,         SHIFT,      LALT,          LALT+SHIFT,  RALT,      RALT+SHIFT
	key <AC01> { [            c,  C,          ccedilla,      Ccedilla,    NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol ] }; // cC
	key <AC02> { [            i,  I ,         idotless,      Iabovedot,   NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol] }; // iI
	key <AC03> { [            e,  E,          odiaeresis,    Odiaeresis,  NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol ] }; // eE
	key <AC04> { [            a,  A,          udiaeresis,    Udiaeresis,  NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol ] }; // aA
	key <AC05> { [        comma,  semicolon,  scedilla,      Scedilla,    NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol ] }; // ,   ;
	key <AC06> { [       period,  colon,      Delete,        NoSymbol,    NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol ] }; // .:
	key <AC07> { [            h,  H,          Left,          BackSpace,   NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol ] }; // hH
	key <AC08> { [            t,  T,          Down,          Tab,         NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol ] }; // tT
	key <AC09> { [            s,  S,          Up,            Return,      NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol ] }; // sS
	key <AC10> { [            n,  N,          Right,         NoSymbol,      NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol ] }; // nN
	key <AC11> { [            q,  Q,          bracketright,  braceright,  NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol] }; // qQ

//                BASE,         SHIFT,       LALT,      LALT+SHIFT,  RALT,      RALT+SHIFT
	key <AB01> { [            g,  G,           NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol ] }; // gG
	key <AB02> { [            x,  X,           NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol ] }; // xX
	key <AB03> { [            j,  J,           NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol ] }; // jJ
	key <AB04> { [            k,  K,           NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol] }; // kK
	key <AB05> { [        minus,  underscore,  NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol ] }; // -_
	key <AB06> { [     question,  exclam,      NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol ] }; // ?!
	key <AB07> { [            r,  R,           NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol ] }; // rR
	key <AB08> { [            m,  M,           NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol ] }; // mM
	key <AB09> { [            f,  F,           NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol ] }; // fF
	key <AB10> { [            p,  P,           NoSymbol,  NoSymbol,    NoSymbol,  NoSymbol,   NoSymbol,  NoSymbol ] }; // pP
key <DELE> {[ delete,           delete]};
};
//ENGRAM//END

**Comment by binarybottle** [comment]
Very nice, @caga, thank you for these interesting additions!

(I use macos and popos.)

**Comment by binarybottle** [comment]
@caga -- Since this is more of a discussion than an issue (Engram installs nicely on linux), please feel free to move to Discussioni (https://github.com/binarybottle/engram/discussions).  I will close this issue in the meantime.
