### ISSUE TITLE
Delete key not working on the linux Keyman distribution of the Engram layout

### ISSUE THREAD

**Issue by binarybottle** [binarybottle/engram#21]
I am able to use the Delete key with the Keyman distribution of the Engram layout on macos, but not on linux.  Any suggestions for a fix?  @sunaku, @Tristen-Sinanju, @caga?

**Comment by sunaku** [comment]
The delete key isn't remapped in our XKB file, so it should be inherited from the standard US (basic) layout.

Can you try running `xev` in a graphical terminal and then press the delete key?  I get this output on my side:

```
KeyPress event, serial 37, synthetic NO, window 0x7800001,
    root 0x6ab, subw 0x0, time 14982585, (-248,-19), root:(623,459),
    state 0x2000, keycode 119 (keysym 0xffff, Delete), same_screen YES,
    XLookupString gives 1 bytes: (7f) ""
    XmbLookupString gives 1 bytes: (7f) ""
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x7800001,
    root 0x6ab, subw 0x0, time 14982663, (-248,-19), root:(623,459),
    state 0x2000, keycode 119 (keysym 0xffff, Delete), same_screen YES,
    XLookupString gives 1 bytes: (7f) ""
    XFilterEvent returns: False
```

**Comment by binarybottle** [comment]
> KeyRelease event, serial 36, synthetic NO, window 0x5600001,
>     root 0x7bf, subw 0x0, time 11276225, (1038,456), root:(1038,485),
>     state 0x0, keycode 36 (keysym 0xff0d, Return), same_screen YES,
> "   XLookupString gives 1 bytes: (0d) "
>     XFilterEvent returns: False
>

**Comment by sunaku** [comment]
Hmm, that looks correct to me.  Maybe something else is interpreting your delete key?

Are you running `ibus` (for the keyman version of Engram) alongside the XKB version?

See https://discourse.gnome.org/t/delete-key-not-working/5627/3

**Comment by binarybottle** [comment]
Thank you, @sunaku, but I don't have a ~/.cache/ibus/compose/ directory.

Also, to be clear, I'm not currently using your xkb file; I'm using Keyman to remap keys.

**Comment by sunaku** [comment]
Thanks for clarifying - I really was thinking this was an issue with my XKB implementation so far! :sweat_smile: 

Do you have dead keys enabled in your IBus config?  It's another symptom in that Gnome bug report.

**Comment by binarybottle** [comment]
Got it -- thanks!  Until Keyman fixes this, I'll recommend people use setxkbmap:

linux ➤ setxkbmap -query                                                                  git:master
rules:      evdev
model:      pc101
layout:     us,us
variant:    engram,basic
linux ➤ setxkbmap -layout us,us -variant engram,basic -option grp:ctrls_toggle
