### ISSUE TITLE
Angle Mod

### ISSUE THREAD

**Issue by Userwithaname** [binarybottle/engram#24]
I am using a modified version of your layout, and I thought I would share it here. The changes were intended to make the layout more symmetrical on regular horizontally staggered keyboards.

- Shifted the ?RMFP keys to the left by one (I find them easier to reach)
- Swapped the `>` and `^` keys
- Swapped the `]` and `/` keys

The resulting modified layout looks like this:

![engram-angle-mod](https://user-images.githubusercontent.com/42674728/123987500-894a4f80-d9c7-11eb-96e8-2619532a6920.png)

PS: Thank you for this amazing layout!

**Comment by binarybottle** [comment]
Very nice!  
I can see why you would like these modifications for a staggered keyboard.  
Thank you for sharing!
