### ISSUE TITLE
Layouts are versioned, but that's unclear

### ISSUE THREAD

**Issue by lindes** [binarybottle/engram#35]
Hi there,

It seems like there have been different versions of this actual layout over time.  This is great, in as much as I presume it's based on learning over time, and continuing to optimize the layout based on new ideas, evidence, reflections, what have you.

However, I notice a source of confusion in this.  I've found various pages out in the world with images of what they're calling the engram layout, which don't match the layout described on this page.  As far as I can tell, they _do_ match earlier versions of the layout... But the main README here makes very little indication that there even are different versions (it's alluded to in reference to the "preprint", but that could easily be considered a reference to a version of that article, rather than a version of the layout itself), let alone what the history is of the different layouts, what old versions looked like, etc.

I noticed some references to some sort of version numbering in commit messages... I guess the current layout is v2.0, and was preceded by v1.3, etc.?  But this info doesn't say "this is version X" or similar, and the only tags on the repo are for 0.x-alpha versions.

So, I humbly suggest the following:

1. Make it clear in the readme (and main website) that there exist different versions of the layout (so people know to be on the lookout for version numbers);
2. Enumerate what those versions have been over time, displaying the full layout for each (so that others can identify and name which versions they have in some extant document or config);
3. Add tags for the commits that finalized any given version;
4. Maintain these practices going forward, if/when/as the layout continues to evolve.

Thank you for your consideration!  I'm excited by this layout _and_ how it's being derived.  I believe the latter will be useful to me as I set up a 12-key chording keyboard, and the former I may well use or adapt for a (somewhat, at least) more traditional keyboard in the future.

**Comment by binarybottle** [comment]
Thank you, @lindes, for your thoughtful recommendations!  I really appreciate it, and agree that it is important to make sure that versioning is clearly documented.  I am a bit buried right now with work, but will follow up on these when I have time.

**Comment by binarybottle** [comment]
@lindes -- Thank you again for you suggestions!  I have created v1.3 and v2 tags and corresponding releases with full layouts in their descriptions, updated the README, Jupyter notebook, and engram.dev website.

**Comment by lindes** [comment]
Thanks, Arno!  Looks good!
