### ISSUE TITLE
Consider thumbs, typos, and Backspace/Enter/Modifiers in optimization algorithm

### ISSUE THREAD

**Issue by eugenesvk** [binarybottle/engram#40]
I've noticed that you have a layout for an ["Ergonomic" orthonormal keyboard](https://github.com/binarybottle/engram/blob/master/assets/engram-ergo-squeezed-800px.png?raw=true).
Currently it simply __repeats__ the layout of the dumb old __standard__ layout, however there is a huge advantage of an "ergonomic" orthonormal layout: you can use your two strongest fingers — 👍 __thumbs__ 👍 — to do more useful stuff besides pressing <kbd>Space</kbd>! So repeating a layout optimized for the standard layout that ignores thumbs outside of <kbd>Space</kbd> is suboptimal

In a similar fashion, the location of some very frequently used keys crucial to any typing (<kbd>Backspace</kbd> and to a lesser extent <kbd>Enter</kbd>) doesn't seem to be reflected in optimizations and even in the __data sources__ — the text corpus is assumed to having been typed perfectly __without intermediate typos__ (and  paragraph newlines?)
This would also be great to have in an "Ergonomic" layout since many such layouts do move these keys around, so it'd be great to have some more solid optimization-based algorithmic ground as to where to move those keys to.

Would you be able to adjust your algorithms to take the 👍 __thumbs__, __typos__ and __non-letter text entry keys__ into account and shift more keys around to get closer to the ultimate typing convenience?
(though it might be better to use an even more ergonomic layout of the thumb keys in a "fan-like" when computing the "easy and comfortable" factors)

**Comment by Tristen-Sinanju** [comment]
Here was my solution... Though I swapped 'v-thumb' and 'q' 
layer0 lowercase
Layer1 uppercase
Layer2 symbols, numbers, keyboard-shortcuts
Layer3 mouse and f-keys
Layer4 numpad 

Partially since I only have 40% keyboard to work with, lol


![125207181-7d288280-e250-11eb-896d-5afc424a564b](https://user-images.githubusercontent.com/84834000/148641830-f642f03f-f308-4a3d-a273-a7c0881a9d42.png)

**Comment by binarybottle** [comment]
Thank you for writing, @eugenesvk!

Re: "it simply repeats the layout of the dumb old standard layout", I prefer to distinguish between "keyboard layout" to mean the mapping of characters to keys, and "keyboard design" to refer to the positioning of the physical keys. You are referring to the latter, and for letter characters, I have restricted my work on the Engram to try and optimize the former. It is clear that once you place the letter "E", for example, where the thumb can access it, the game changes.  You are more than welcome to extend the Engram analysis to account for these added degrees of freedom!

And you are absolutely correct that none of the text corpus data sources, to my knowledge, capture intermediate typos.

**Comment by eugenesvk** [comment]
> have restricted my work on the Engram to try and optimize the former.

why though leave such a big chunk of potential improvement on the table?
We know that the default keyboard design is just as dumb as the default keymap layout; and whoever decides to jump the `QWERTY` ship would get a huge benefit anyway even if the "perfect" keymap layout is designed for the "perfect" keyboard design and then backported with minimal tweaks (for consistency) to account for the lack of thumbs (or maybe not, maybe it's much better to have `E` on a <kbd>Space</kbd>-adjacent <kbd>Alt</kbd>)

> You are more than welcome to extend the Engram analysis to account for these added degrees of freedom!

Thanks, though that requires a bit :) more keyboard expertise than I have, so hopefully the next iteration of the keyboard research/design will take these issues into account

**Comment by binarybottle** [comment]
> why though leave such a big chunk of potential improvement on the table?

Most people will never leave the keyboard that comes bundled with their computer/laptop, so I wanted to reach this audience first.

**Comment by binarybottle** [comment]
I forgot to add that I type on Kinesis Advantage Pro and ZSA Moonlander orthonormal keyboards, so frequent command keys are at my thumbtips!
