### ISSUE TITLE
macOS - Keyman doesn't work; use Karabiner

### ISSUE THREAD

**Issue by sunaku** [binarybottle/engram#55]
@willpuckett writes in [*Exploring the Engram Keyboard Layout*](https://smote.io/engram):
> The Keyman App reccommended on the Engram website ***doesn't work with newer versions of MacOS***, so I threw together a keymap for [Karabiner](https://karabiner-elements.pqrs.org/). You can try it out [here](https://smote.io/static/engram.json) (place the json file in `~/.config/karabiner/assets/complex_modifications/` and maybe restart Karabiner).

**Comment by willpuckett** [comment]
Thanks for the mention! Just added an [x-callback-url as well to simplify things for people](https://smote.io/install_engram.html).

**Comment by binarybottle** [comment]
Thank you for the pointer, @sunaku, and thank you for contributing the Karabiner keymap, @willpuckett!

**Comment by willpuckett** [comment]
off topic, but the originally linked post now includes a keymap for use on iOS as well... there are layouts for iPhone and iPad.

**Comment by binarybottle** [comment]
Amazing -- thank you, @willpuckett!

**Comment by sunaku** [comment]
@willpuckett - would you mind if we imported your Karabiner configuration file into this repo?

**Comment by willpuckett** [comment]
Of course that's fine or I can submit a PRif you prefer.

**Comment by sunaku** [comment]
Most excellent, please do! :+1:  I think a good spot for it might be under the `install/mac/karabiner/` directory tree.

**Comment by willpuckett** [comment]
It's open [here](https://github.com/binarybottle/engram/pull/56).

**Comment by willpuckett** [comment]
Thanks for the merge I think this issue can be closed now
