### ISSUE TITLE
why not a symmetrical layout?

### ISSUE THREAD

**Issue by unit-5370** [binarybottle/engram#66]
maybe i did not paid attention or did not understood but why not set a symmetrical layout, passing Q or Z at the side of B?

**Comment by unit-5370** [comment]
ok! Q and Z were accounted arbitrary? different positions for them effects the layout?

**Comment by binarybottle** [comment]
Z is less common in English than Q, so it is placed in the most difficult location (lateral pinkie extension off the home row.).
