### ISSUE TITLE
How many versions will you make ? ! :)

### ISSUE THREAD

**Issue by caga** [binarybottle/engram#8]
My dearest friend,

First of all i want to state that, maybe to your surprise (or not), i write this lines using your layout (version 1).
 
I find out your work maybe on very first days, i loved it and made a (crazy?) decision and changed my layout for the best !!! :)
After 20 days of working and learning i reached 50 wpm on your layout. :) i even prepare xkb (linux) layout based on yours. i was thinking to publish it on my github page for the ones who want to use your layout on linux.

Now i learned you had 2 other versions (3.rd one even submitted an hour before). 
So please pity me... :)  should i begin to learn your final version or do you also have plans to work further and optimise/change it again ?

i wish you a happy day and looking forward to your answer before writing a new linux layout and begin to practise it.

PS: Can You also give the performance comparion table (same two tables on readme you gave) between your versions

**Comment by binarybottle** [comment]
Thank you so much for your interest, @caga!  I'm so happy to hear that you are using an early version of the Engram layout!

You will be happy to hear that I am staging a showdown this week between the three versions of Engram to see who is the winner, based on finger metrics...

**Comment by caga** [comment]
Thanks a lot :) i am looking forward to it.

**Comment by caga** [comment]
And I am here to see comparison  :) .

Scores are very close huh? 

What do you recommend for me to use? i mean i really used to version 1 but if you say version 2 or 3 is more comfortable, then i can give a try to learn. It seems you stick on version 2(?). What i search is comfort but then speed.  finger inward and backward movements (especially for pinkys) are also important :)
Thank you again for this beautiful as well as useful research. 
Peace be on to you.

**Comment by binarybottle** [comment]
@caga -- Thank you for your continued interest!  As you can see, I have been putting a lot of effort into making this decision myself, but rest assured -- I plan on making a decision this weekend after updating a couple of functions and reviewing the results of my analyses...

**Comment by wpbrown** [comment]
Does the h and r swap feel better in practice? I just started learning and the home row roll inward on TH feels like one of engram’s super powers.

**Comment by binarybottle** [comment]
I have been debating this, and the main reason I'm considering TR instead of TH is because R has a much higher frequency than H, so placing it on the home row supports other bigrams.

**Comment by wpbrown** [comment]
Norvig and other common frequency listings only have r ~1% higher than h, but I know you have many more fancy corpus to look at. As for bigrams TH is off the charts. It feels good to my fingers despite the math I suppose.

**Comment by binarybottle** [comment]
Excellent point. Perhaps I am relying to much on the absolute (224 vs 180 billion) as opposed to the relative (6.28 vs 5.05%) differences.  I will take another look into this today....

**Comment by binarybottle** [comment]
@caga and @wpbrown -- I am happy to inform you that after a lot more thinking, coding, analyzing, and evaluating, I came full circle to Engram v2.0, which has been updated on the website (engram.dev) and in the jupyter notebook.  Enjoy!

And @wpbrown -- Thank you very much for that final nudge toward TH in the home row.  
 There were two optimized layouts tied for first place, and choosing the one with TR was somewhat arbitrary, so I switched to the other one with superpowers ;)

**Comment by caga** [comment]
I am about to get my plank keyboard clone next week and will be happy to use this very efficient layout of yours on it ... Peace be on you. :) (: Though i have to practice for another month probably before i actuall use it at work efficiently.  :100:

**Comment by binarybottle** [comment]
All the best, @caga!
